# Generated by Django 3.0.6 on 2020-07-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200705_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
