# Generated by Django 3.0.6 on 2020-07-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200712_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Politics', 'Politics'), ('Health', 'Health'), ('Science & Tech.', 'Science & Tech.'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=20),
        ),
    ]
